### ISSUE TITLE
Project not usable?

### ISSUE THREAD

**Issue by toastedcrumpets** [sbordeyne/kanidm-operator#11]
First, I want to say the idea of a kanidm operator is a fantastic one!

I tried to use it as follows, first clone the repo, then
```
$ kubectl kustomize manifests/crds > crds.yaml
$ kubectl kustomize manifests/operator > operator.yaml
$ kubectl apply -f crds.yaml
namespace/kanidm-system created
customresourcedefinition.apiextensions.k8s.io/accounts.kanidm.github.io created
customresourcedefinition.apiextensions.k8s.io/groups.kanidm.github.io created
customresourcedefinition.apiextensions.k8s.io/kanidms.kanidm.github.io created
customresourcedefinition.apiextensions.k8s.io/oauth2-clients.kanidm.github.io created
customresourcedefinition.apiextensions.k8s.io/password-badlists.kanidm.github.io created
customresourcedefinition.apiextensions.k8s.io/service-accounts.kanidm.github.io created
$ kubectl apply -f operator.yaml
namespace/kanidm-system configured
serviceaccount/kanidm-operator-account created
role.rbac.authorization.k8s.io/kanidm-operator-role-namespaced created
clusterrole.rbac.authorization.k8s.io/kanidm-operator-role-cluster created
rolebinding.rbac.authorization.k8s.io/kanidm-operator-rolebinding-namespaced created
clusterrolebinding.rbac.authorization.k8s.io/kanidm-operator-rolebinding-cluster created
deployment.apps/kanidm-operator created
```
Then I try running the example 
```
$ kubectl apply -f manifests/example/kanidm.yaml
error: resource mapping not found for name: "kanidm" namespace: "kanidm" from "manifests/example/kanidm.yaml": no matches for kind "Kanidm" in version "v1alpha1"
ensure CRDs are installed first
```
Which doesn't make sense to me.

I also noticed that the operator pod is having issues terminating with the log
```
exec /root/.local/bin/poetry: exec format error
```

I tried forking, rebuilding the docker image, then deploying but my pod fails a liveness probe and seems to be stuck.

It seems development has halted, but I'd like to help out if I can! I'm a competant python developer, but I've never written a k8s operator before.

**Comment by toastedcrumpets** [comment]
OK I've debugged the first issue, the example manifest needs `apiVersion` to have the group name from the CRD:
```
apiVersion: kanidm.github.io/v1alpha1
kind: Kanidm
metadata:
  name: kanidm
  namespace: kanidm
spec:
  version: 1.2.0
  database:
    fsType: other
    storageClass: longhorn
    storageSize: 1Gi
  domain: idm.example.com
  certificate:
    issuer: cluster-issuer
  logLevel: info
  backup:
    enabled: true
    schedule: "0 9 * * *"
    versions: 7
    storageClass: longhorn
    storageSize: 7Gi
  webPort: 8443
  ldapPort: 3890
  highAvailability:
    enabled: false
    replicas: 1
```
I'll start playing around with the docker image to see why my build isn't responding to liveness probes...
